# Generated by Django 6.0.2 on 2026-03-25 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato_id', models.IntegerField(db_index=True, unique=True)),
                ('score_total', models.IntegerField(default=0)),
                ('score_status', models.IntegerField(default=0)),
                ('score_valor', models.IntegerField(default=0)),
                ('score_divida', models.IntegerField(default=0)),
                ('score_cancelamento', models.IntegerField(default=0)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Score de Lead',
                'verbose_name_plural': 'Score dos Leads',
                'ordering': ['-score_total', '-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('bloqueado', 'Bloqueado'), ('inativo', 'Inativo')], default='ativo', max_length=20)),
                ('data_contratacao', models.DateField(blank=True, null=True)),
                ('ramal', models.CharField(blank=True, max_length=10, null=True)),
                ('ultimo_acesso', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_vendedor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vendedores',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato_id', models.IntegerField(db_index=True)),
                ('data_atribuicao', models.DateTimeField(auto_now_add=True)),
                ('resolvido', models.BooleanField(default=False)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('contato_realizado', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('em_contato', 'Em Contato'), ('em_negociacao', 'Em Negociação'), ('perdido', 'Perdido'), ('venda', 'Venda Realizada'), ('lista_negra', 'Lista Negra')], db_index=True, default='novo', max_length=20)),
                ('status_contato', models.CharField(blank=True, choices=[('desligou', 'Cliente desligou'), ('nao_atendeu', 'Cliente não atendeu'), ('ligar_mais_tarde', 'Ligar mais tarde'), ('caro', 'Cliente achou caro'), ('sem_interesse', 'Cliente não tem interesse'), ('nao_virou_venda', 'Cliente não virou venda'), ('numero_invalido', 'Número inválido'), ('outros', 'Outros')], max_length=30, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('proximo_contato', models.DateTimeField(blank=True, null=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='core.vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('documento', models.CharField(max_length=20)),
                ('registro', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=8)),
                ('logradouro', models.CharField(max_length=250)),
                ('bairro', models.CharField(max_length=250)),
                ('cidade', models.CharField(max_length=250)),
                ('uf', models.CharField(max_length=2)),
                ('celular1', models.CharField(max_length=15)),
                ('celular2', models.CharField(max_length=15)),
                ('telefone1', models.CharField(max_length=15)),
                ('telefone2', models.CharField(max_length=15)),
                ('lead', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lead')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vendedor')),
            ],
        ),
    ]
