# Generated by Django 6.0.2 on 2026-03-16 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato_id', models.IntegerField(db_index=True, unique=True)),
                ('score_total', models.IntegerField(default=0)),
                ('score_status', models.IntegerField(default=0)),
                ('score_valor', models.IntegerField(default=0)),
                ('score_divida', models.IntegerField(default=0)),
                ('score_cancelamento', models.IntegerField(default=0)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Score de Lead',
                'verbose_name_plural': 'Scores de Leads',
                'ordering': ['-score_total', '-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='SessaoLigacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato_id', models.IntegerField(db_index=True)),
                ('status', models.CharField(choices=[('em_andamento', 'Em Andamento'), ('completed', 'Atendida'), ('failed', 'Sem contato')], default='em_andamento', max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TentativaLigacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_discado', models.CharField(max_length=50)),
                ('id_ligacao', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('calling', 'Chamando'), ('completed', 'Atendida'), ('no_answer', 'Sem resposta'), ('failed', 'Falhou')], default='calling', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tentativas', to='core.sessaoligacao')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('bloqueado', 'Bloqueado'), ('inativo', 'Inativo')], default='ativo', max_length=20)),
                ('data_contratacao', models.DateField(blank=True, null=True)),
                ('ramal', models.CharField(blank=True, default='000', max_length=10, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_vendedor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sessaoligacao',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.vendedor'),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato_id', models.IntegerField(db_index=True)),
                ('data_atribuicao', models.DateTimeField(auto_now_add=True)),
                ('resolvido', models.BooleanField(default=False)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('contato_realizado', models.BooleanField(default=False)),
                ('status_contato', models.CharField(blank=True, choices=[('desligou', 'Cliente desligou'), ('caro', 'Cliente achou caro'), ('sem_interesse', 'Cliente não tem interesse'), ('venda', 'Cliente virou venda'), ('nao_atendeu', 'Cliente não atendeu'), ('numero_invalido', 'Número inválido'), ('ligar_mais_tarde', 'Ligar mais tarde'), ('outros', 'Outros')], max_length=30, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('proximo_contato', models.DateTimeField(blank=True, null=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='core.vendedor')),
            ],
        ),
    ]
