# Generated by Django 6.0.2 on 2026-03-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status_contato',
            field=models.CharField(blank=True, choices=[('desligou', 'Cliente desligou'), ('caro', 'Cliente achou caro'), ('sem_interesse', 'Cliente não tem interesse'), ('venda', 'Cliente virou venda'), ('nao_atendeu', 'Cliente não atendeu'), ('nao_virou_venda', 'Cliente não virou venda'), ('numero_invalido', 'Número inválido'), ('ligar_mais_tarde', 'Ligar mais tarde'), ('outros', 'Outros')], max_length=30, null=True),
        ),
    ]
