# Generated by Django 6.0.2 on 2026-03-05 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_claroendereco'),
        ('core', '0002_vendedor_alter_lead_vendedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='contrato_id',
        ),
        migrations.AddField(
            model_name='lead',
            name='contrato',
            field=models.ForeignKey(db_column='contrato', db_constraint=False, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='contratos.contrato'),
            preserve_default=False,
        ),
    ]
