# Generated by Django 6.0.2 on 2026-03-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_lead_resolvido_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='ramal',
            field=models.CharField(blank=True, default='000', max_length=10, null=True),
        ),
    ]
