# Generated by Django 6.0.2 on 2026-03-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vendedor_alter_lead_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='resolvido',
            field=models.BooleanField(default=False),
        ),
    ]
