# Generated by Django 6.0.2 on 2026-03-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_lead_contrato_id_lead_contrato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='contrato',
        ),
        migrations.AddField(
            model_name='lead',
            name='contrato_id',
            field=models.IntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
    ]
