# Generated by Django 6.0.2 on 2026-03-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cliente_lead_cliente_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('novo', 'Novo'), ('em_contato', 'Em Contato'), ('em_negociacao', 'Em Negociação'), ('perdido', 'Perdido'), ('venda', 'Venda Realizada')], db_index=True, default='novo', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status_contato',
            field=models.CharField(blank=True, choices=[('desligou', 'Cliente desligou'), ('nao_atendeu', 'Cliente não atendeu'), ('ligar_mais_tarde', 'Ligar mais tarde'), ('caro', 'Cliente achou caro'), ('sem_interesse', 'Cliente não tem interesse'), ('nao_virou_venda', 'Cliente não virou venda'), ('numero_invalido', 'Número inválido'), ('outros', 'Outros')], max_length=30, null=True),
        ),
    ]
