# Generated by Django 6.0.2 on 2026-03-10 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ligacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoLigacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato_id', models.IntegerField(db_index=True)),
                ('status', models.CharField(choices=[('em_andamento', 'Em Andamento'), ('completed', 'Atendida'), ('failed', 'Sem contato')], default='em_andamento', max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='TentativaLigacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_discado', models.CharField(max_length=50)),
                ('id_ligacao', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('calling', 'Chamando'), ('completed', 'Atendida'), ('no_answer', 'Sem resposta'), ('failed', 'Falhou')], default='calling', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tentativas', to='core.sessaoligacao')),
            ],
        ),
        migrations.DeleteModel(
            name='Ligacao',
        ),
    ]
