# Generated by Django 6.0.2 on 2026-03-19 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lead_status_alter_lead_status_contato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tentativaligacao',
            name='sessao',
        ),
        migrations.DeleteModel(
            name='SessaoLigacao',
        ),
        migrations.DeleteModel(
            name='TentativaLigacao',
        ),
    ]
