# Generated by Django 6.0.2 on 2026-03-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sessaoligacao_tentativaligacao_delete_ligacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='contato_realizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='proximo_contato',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='status_contato',
            field=models.CharField(blank=True, choices=[('desligou', 'Cliente desligou'), ('caro', 'Cliente achou caro'), ('sem_interesse', 'Cliente não tem interesse'), ('venda', 'Cliente virou venda'), ('nao_atendeu', 'Cliente não atendeu'), ('numero_invalido', 'Número inválido'), ('outros', 'Outros')], max_length=30, null=True),
        ),
    ]
