# Generated by Django 6.0.2 on 2026-03-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_tentativaligacao_sessao_delete_sessaoligacao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scorelead',
            options={'ordering': ['-score_total', '-atualizado_em'], 'verbose_name': 'Score de Lead', 'verbose_name_plural': 'Score dos Leads'},
        ),
        migrations.AlterModelOptions(
            name='vendedor',
            options={'verbose_name_plural': 'Vendedores'},
        ),
        migrations.AddField(
            model_name='vendedor',
            name='ultimo_acesso',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
