# Generated by Django 6.0.2 on 2026-03-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sessaoligacao_tentativaligacao_delete_ligacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato_id', models.IntegerField(db_index=True, unique=True)),
                ('score_total', models.IntegerField(default=0)),
                ('score_status', models.IntegerField(default=0)),
                ('score_valor', models.IntegerField(default=0)),
                ('score_divida', models.IntegerField(default=0)),
                ('score_cancelamento', models.IntegerField(default=0)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Score de Lead',
                'verbose_name_plural': 'Scores de Leads',
                'ordering': ['-score_total', '-atualizado_em'],
            },
        ),
    ]
