# Generated by Django 6.0.2 on 2026-03-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_scorelead_options_alter_vendedor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='ramal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
