# Generated by Django 6.0.2 on 2026-03-25 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TentativaContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=64, unique=True)),
                ('ramal', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_discado', models.CharField(blank=True, max_length=20, null=True)),
                ('iniciada_em', models.DateTimeField(blank=True, null=True)),
                ('atendida_em', models.DateTimeField(blank=True, null=True)),
                ('finalizada_em', models.DateTimeField(blank=True, null=True)),
                ('duracao', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('atendida', 'Atendida'), ('sem_resposta', 'Sem resposta'), ('ocupado', 'Ocupado'), ('falha', 'Falha'), ('cancelada', 'Cancelada'), ('desconhecido', 'Desconhecido')], default='pendente', max_length=20)),
                ('hangup_text', models.CharField(blank=True, max_length=50, null=True)),
                ('hangup_code', models.IntegerField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas', to='core.lead')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vendedor')),
            ],
        ),
    ]
