# Generated by Django 6.0.2 on 2026-03-19 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_remove_tentativaligacao_sessao_delete_sessaoligacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoLigacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato_id', models.IntegerField(db_index=True)),
                ('status', models.CharField(choices=[('em_andamento', 'Em Andamento'), ('atendida', 'Atendida'), ('sem_resposta', 'Sem Resposta'), ('falha', 'Falha'), ('parcial', 'Parcial')], default='em_andamento', max_length=50)),
                ('numero_atendido', models.CharField(blank=True, max_length=20, null=True)),
                ('tentativa_atendida', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizad_em', models.DateTimeField(blank=True, null=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='TentativaLigacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_numero', models.CharField(choices=[('celular1', 'Celular 1'), ('celular2', 'Celular 2'), ('telefone1', 'Telefone 1'), ('telefone2', 'Telefone 2')], max_length=20)),
                ('numero', models.CharField(max_length=20)),
                ('ordem', models.PositiveSmallIntegerField()),
                ('ligacao_id', models.CharField(blank=True, max_length=120, null=True)),
                ('uniqueid', models.CharField(blank=True, max_length=150, null=True)),
                ('linkedid', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('atendida', 'Atendida'), ('sem_resposta', 'Sem resposta'), ('ocupado', 'Ocupado'), ('falha', 'Falha'), ('numero_invalido', 'Número inválido'), ('desconhecido', 'Desconhecido')], default='pendente', max_length=20)),
                ('status_api', models.CharField(blank=True, max_length=50, null=True)),
                ('disposition_cdr', models.CharField(blank=True, max_length=50, null=True)),
                ('billsec', models.PositiveIntegerField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('payload_api', models.JSONField(blank=True, null=True)),
                ('detalhes_cel', models.JSONField(blank=True, null=True)),
                ('iniciada_em', models.DateTimeField(blank=True, null=True)),
                ('finalizada_em', models.DateTimeField(blank=True, null=True)),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas', to='comunicacao.sessaoligacao')),
            ],
        ),
    ]
