# Generated by Django 6.0.2 on 2026-03-19 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessaoligacao',
            options={'verbose_name_plural': 'Sessões de Ligação'},
        ),
        migrations.AlterModelOptions(
            name='tentativaligacao',
            options={'verbose_name_plural': 'Tentativas de Ligação'},
        ),
    ]
