# Generated by Django 6.0.2 on 2026-03-23 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacao', '0002_alter_sessaoligacao_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tentativaligacao',
            name='sessao',
        ),
        migrations.DeleteModel(
            name='SessaoLigacao',
        ),
        migrations.DeleteModel(
            name='TentativaLigacao',
        ),
    ]
