# Generated by Django 6.0.2 on 2026-02-27 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('contrato', models.IntegerField(db_column='Contrato', primary_key=True, serialize=False)),
                ('cid', models.CharField(blank=True, db_column='CID', max_length=255, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=255, null=True)),
                ('valor', models.DecimalField(blank=True, db_column='Valor', decimal_places=2, max_digits=20, null=True)),
                ('devedor', models.DecimalField(blank=True, db_column='Devedor', decimal_places=2, max_digits=20, null=True)),
                ('produto', models.CharField(blank=True, db_column='Produto', max_length=255, null=True)),
                ('velocidade', models.CharField(blank=True, db_column='Velocidade', max_length=255, null=True)),
                ('ativacao', models.DateField(blank=True, db_column='Ativacao', null=True)),
                ('registro', models.CharField(blank=True, db_column='Registro', max_length=255, null=True)),
                ('doc', models.CharField(blank=True, db_column='DOC', max_length=255, null=True)),
                ('nome', models.CharField(blank=True, db_column='NOME', max_length=255, null=True)),
                ('unidade', models.CharField(blank=True, db_column='Unidade', max_length=255, null=True)),
                ('cancelamento', models.DateField(blank=True, db_column='Cancelamento', null=True)),
                ('endereco', models.CharField(blank=True, db_column='Endereco', max_length=255, null=True)),
                ('numero', models.CharField(blank=True, db_column='Numero', max_length=255, null=True)),
                ('complemento', models.CharField(blank=True, db_column='Complemento', max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, db_column='Bairro', max_length=255, null=True)),
                ('cidade', models.CharField(blank=True, db_column='Cidade', max_length=255, null=True)),
                ('uf', models.CharField(blank=True, db_column='UF', max_length=255, null=True)),
                ('cep', models.CharField(blank=True, db_column='CEP', max_length=255, null=True)),
                ('cadastro', models.DateField(blank=True, db_column='Cadastro', null=True)),
                ('canal', models.CharField(blank=True, db_column='CANAL', max_length=255, null=True)),
                ('origem', models.CharField(blank=True, db_column='ORIGEM', max_length=255, null=True)),
                ('telefone1', models.CharField(blank=True, max_length=50, null=True)),
                ('telefone2', models.CharField(blank=True, max_length=50, null=True)),
                ('celular1', models.CharField(blank=True, max_length=50, null=True)),
                ('celular2', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'contratos',
                'managed': False,
            },
        ),
    ]
