# Generated by Django 6.0.2 on 2026-03-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaCdr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agente', models.CharField(blank=True, max_length=255, null=True)),
                ('destino', models.CharField(blank=True, max_length=255, null=True)),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('atendimento', models.DateTimeField(blank=True, null=True)),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('duracao', models.IntegerField(blank=True, null=True)),
                ('hangup_text', models.CharField(blank=True, max_length=255, null=True)),
                ('hangup_cause', models.CharField(blank=True, max_length=255, null=True)),
                ('gravacao', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('vendedor_id', models.IntegerField(blank=True, null=True)),
                ('vendedor_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('contrato_numero', models.IntegerField(blank=True, null=True)),
                ('contrato_doc', models.CharField(blank=True, max_length=255, null=True)),
                ('contrato_nome', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Auditoria CDR',
                'db_table': 'auditoria_cdr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditoriaChamadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=64, null=True)),
                ('datahora', models.DateTimeField(blank=True, null=True)),
                ('agente', models.CharField(blank=True, max_length=20, null=True)),
                ('destino', models.CharField(blank=True, max_length=20, null=True)),
                ('evento', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'auditoria_chamadas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClaroEndereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('num_cep', models.CharField(blank=True, max_length=8, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=200, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('livres', models.IntegerField(blank=True, null=True)),
                ('penetracao', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Endereços',
                'db_table': 'claro_enderecos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('contrato', models.IntegerField(db_column='Contrato', primary_key=True, serialize=False)),
                ('cid', models.CharField(blank=True, db_column='CID', max_length=255, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=255, null=True)),
                ('valor', models.DecimalField(blank=True, db_column='Valor', decimal_places=2, max_digits=20, null=True)),
                ('devedor', models.DecimalField(blank=True, db_column='Devedor', decimal_places=2, max_digits=20, null=True)),
                ('produto', models.CharField(blank=True, db_column='Produto', max_length=255, null=True)),
                ('velocidade', models.CharField(blank=True, db_column='Velocidade', max_length=255, null=True)),
                ('ativacao', models.DateField(blank=True, db_column='Ativacao', null=True)),
                ('registro', models.CharField(blank=True, db_column='Registro', max_length=255, null=True)),
                ('doc', models.CharField(blank=True, db_column='DOC', max_length=255, null=True)),
                ('nome', models.CharField(blank=True, db_column='NOME', max_length=255, null=True)),
                ('unidade', models.CharField(blank=True, db_column='Unidade', max_length=255, null=True)),
                ('cancelamento', models.DateField(blank=True, db_column='Cancelamento', null=True)),
                ('motivo_cancelamento', models.CharField(blank=True, db_column='MotivoCancelamento', max_length=800, null=True)),
                ('endereco', models.CharField(blank=True, db_column='Endereco', max_length=255, null=True)),
                ('numero', models.CharField(blank=True, db_column='Numero', max_length=255, null=True)),
                ('complemento', models.CharField(blank=True, db_column='Complemento', max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, db_column='Bairro', max_length=255, null=True)),
                ('cidade', models.CharField(blank=True, db_column='Cidade', max_length=255, null=True)),
                ('uf', models.CharField(blank=True, db_column='UF', max_length=255, null=True)),
                ('cep', models.CharField(blank=True, db_column='CEP', max_length=255, null=True)),
                ('cadastro', models.DateField(blank=True, db_column='Cadastro', null=True)),
                ('canal', models.CharField(blank=True, db_column='CANAL', max_length=255, null=True)),
                ('origem', models.CharField(blank=True, db_column='ORIGEM', max_length=255, null=True)),
                ('telefone1', models.CharField(blank=True, max_length=50, null=True)),
                ('telefone2', models.CharField(blank=True, max_length=50, null=True)),
                ('celular1', models.CharField(blank=True, max_length=50, null=True)),
                ('celular2', models.CharField(blank=True, max_length=50, null=True)),
                ('ultima_atualizacao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contratos',
                'managed': False,
            },
        ),
    ]
