# Generated by Django 6.0.2 on 2026-03-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaroEndereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('num_cep', models.CharField(blank=True, max_length=8, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=200, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('livres', models.IntegerField(blank=True, null=True)),
                ('penetracao', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'claro_enderecos',
                'managed': False,
            },
        ),
    ]
