# Generated by Django 6.0.2 on 2026-03-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cdr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calldate', models.DateTimeField()),
                ('clid', models.CharField(max_length=80)),
                ('src', models.CharField(max_length=80)),
                ('dst', models.CharField(max_length=80)),
                ('dcontext', models.CharField(max_length=80)),
                ('channel', models.CharField(max_length=80)),
                ('dstchannel', models.CharField(max_length=80)),
                ('lastapp', models.CharField(max_length=80)),
                ('lastdata', models.CharField(max_length=80)),
                ('duration', models.IntegerField()),
                ('billsec', models.IntegerField()),
                ('disposition', models.CharField(max_length=45)),
                ('amaflags', models.IntegerField()),
                ('accountcode', models.CharField(max_length=20)),
                ('uniqueid', models.CharField(max_length=32)),
                ('userfield', models.CharField(max_length=255)),
                ('did', models.CharField(max_length=50)),
                ('recordingfile', models.CharField(max_length=255)),
                ('cnum', models.CharField(max_length=80)),
                ('cnam', models.CharField(max_length=80)),
                ('outbound_cnum', models.CharField(max_length=80)),
                ('outbound_cnam', models.CharField(max_length=80)),
                ('dst_cnam', models.CharField(max_length=80)),
                ('linkedid', models.CharField(max_length=32)),
                ('peeraccount', models.CharField(max_length=80)),
                ('sequence', models.IntegerField()),
            ],
            options={
                'db_table': 'cdr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventtype', models.CharField(max_length=30)),
                ('eventtime', models.DateTimeField()),
                ('cid_name', models.CharField(max_length=80)),
                ('cid_num', models.CharField(max_length=80)),
                ('cid_ani', models.CharField(max_length=80)),
                ('cid_rdnis', models.CharField(max_length=80)),
                ('cid_dnid', models.CharField(max_length=80)),
                ('exten', models.CharField(max_length=80)),
                ('context', models.CharField(max_length=80)),
                ('channame', models.CharField(max_length=80)),
                ('appname', models.CharField(max_length=80)),
                ('appdata', models.CharField(max_length=240)),
                ('amaflags', models.IntegerField()),
                ('accountcode', models.CharField(max_length=20)),
                ('uniqueid', models.CharField(max_length=32)),
                ('linkedid', models.CharField(max_length=32)),
                ('peer', models.CharField(max_length=80)),
                ('userdeftype', models.CharField(max_length=255)),
                ('eventextra', models.CharField(max_length=255)),
                ('userfield', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'cel',
                'managed': False,
            },
        ),
    ]
