# Generated by Django 6.0.2 on 2026-03-19 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_cdr_cel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cdr',
            options={'managed': False, 'verbose_name_plural': 'Status Finais das Ligações'},
        ),
        migrations.AlterModelOptions(
            name='claroendereco',
            options={'managed': False, 'verbose_name_plural': 'Endereços'},
        ),
    ]
