# Generated by Django 6.0.2 on 2026-03-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_alter_cdr_options_alter_claroendereco_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaCdr',
            fields=[
                ('uuid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('agente', models.CharField(blank=True, max_length=20, null=True)),
                ('destino', models.CharField(blank=True, max_length=20, null=True)),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('atendimento', models.DateTimeField(blank=True, null=True)),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('duracao', models.IntegerField(blank=True, null=True)),
                ('hangup_text', models.CharField(blank=True, max_length=50, null=True)),
                ('hangup_code', models.IntegerField(blank=True, null=True)),
                ('gravacao', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('vendedor_id', models.IntegerField(blank=True, null=True)),
                ('vendedor_nome', models.CharField(blank=True, max_length=150, null=True)),
                ('contrato_numero', models.CharField(blank=True, max_length=50, null=True)),
                ('contrato_doc', models.CharField(blank=True, max_length=30, null=True)),
                ('contrato_nome', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'auditoria_cdr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditoriaChamadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=64, null=True)),
                ('datahora', models.DateTimeField(blank=True, null=True)),
                ('agente', models.CharField(blank=True, max_length=20, null=True)),
                ('destino', models.CharField(blank=True, max_length=20, null=True)),
                ('evento', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'auditoria_chamadas',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Cdr',
        ),
        migrations.DeleteModel(
            name='Cel',
        ),
    ]
